### ISSUE TITLE
question about sft

### ISSUE THREAD

**Issue by hljjjmssyh** [chuhac/ATM-RAG#2]
The format of the raw data is inconsistent with the process of SFT data preprocessing.
https://github.com/chuhac/ATM-RAG/blob/8318fd30a470bc0bc259a142d07f4a1432915c26/atm_train/generator_sft/generator_sft_data_prepare.py#L189
https://github.com/chuhac/ATM-RAG/blob/8318fd30a470bc0bc259a142d07f4a1432915c26/atm_train/generator_sft/generator_sft_data_prepare.py#L53

{
  "question":"What is George Rankin's occupation?",
  "answers":["politician", "political leader", "political figure", "polit.", "pol"],
  "ctxs":[
    {"hasanswer":true,"id":"15165852","score":"1.615642","text":"appealed for support as a tribute to their fathers. Feilden was re-elected at the 1874 general election, and held the seat until his death in 1875 aged 57. Henry Feilden (Conservative politician) Henry Master Feilden (21 February 1818 \u2013 5 September 1875) was an English Conservative Party politician. On 16 March 1869, the result of the 1868 general election in the borough of Blackburn was declared null and void, after an election petition had been lodged. The two Conservatives who had been elected, William Henry Hornby and Feilden's father Joseph Feilden, were unseated when Mr Justice Willes found that there","title":"Henry Feilden (Conservative politician)"},
    {"hasanswer":true,"id":"15165851","score":"1.5857865","text":"Henry Feilden (Conservative politician) Henry Master Feilden (21 February 1818 \u2013 5 September 1875) was an English Conservative Party politician. On 16 March 1869, the result of the 1868 general election in the borough of Blackburn was declared null and void, after an election petition had been lodged. The two Conservatives who had been elected, William Henry Hornby and Feilden's father Joseph Feilden, were unseated when Mr Justice Willes found that there had been widespread intimidation of voters. Henry Feilden was elected at the resulting by-election on 31 March 1869, along with William Henry Hornby's son Edward. Both candidates had","title":"Henry Feilden (Conservative politician)"},
    ...
    {"hasanswer":false,"id":"14398759","score":"1.5703722","text":"Feilden married Julia, daughter of Judge David James McCord (1797\u20131855) of South Carolina. In 1880 Feilden settled in Wells-next-the-Sea, Norfolk. Feilden joined the Norfolk and Norwich Naturalists' Society in 1880 and became President in 1885. He lived in Norfolk for over 20 years, moving to Burwash, Sussex in 1902. One of his discoveries in 1888 was a stuffed specimen of the Great Bustard which had been shot in Norfolk. Feilden contributed to \"Transactions of the Norfolk and Norwich Naturalists' Society\" and submitted scientific papers to \"The Zoologist\" and \"Ibis\" (the journal of the British Ornithologists' Union, to which he was","title":"Henry Wemyss Feilden"}
  ]
}

**Comment by chuhac** [comment]
Hi @hljjjmssyh ,
Thanks for pointing out, we may need to convert the data format in advance.
Try this:
```python
dict_of_lists = {key: [d[key] for d in example["ctxs"]] for key in example["ctxs"][0]}
example["passages"] = {}
example["passages"]["is_selected"] = dict_of_lists["hasanswer"]
example["passages"]["passage_text"] = dict_of_lists["text"]
```
Best,
